# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nationality' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase'
pod 'Firebase/Database’
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'AFNetworking', '~> 2.5'
pod 'SVProgressHUD-0.8.1'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'SDWebImage-ProgressView'
  # Pods for Nationality

end
